### ISSUE TITLE
Bug with domain intel

### ISSUE THREAD

**Issue by Te-k** [Te-k/harpoon#109]
Bug with date format apparently : 

```
----------------- Passive DNS
Traceback (most recent call last):
  File "/home/user/env/default3/bin/harpoon", line 11, in <module>
    load_entry_point('harpoon', 'console_scripts', 'harpoon')()
  File "/home/user/projects/harpoon/harpoon/main.py", line 61, in main
    plugins[args.command].run(config, args, plugins)
  File "/home/user/projects/harpoon/harpoon/commands/domain.py", line 354, in run
    for r in sorted(passive_dns, key=lambda x: x["first"], reverse=True):
TypeError: can't compare offset-naive and offset-aware datetimes
```

**Comment by Te-k** [comment]
`harpoon domain intel stackoverflow.com` raises this bug for instance

**Comment by Te-k** [comment]
Fixed, let me know if it works for you, I will need to push a new version to pypi at some point.
