### ISSUE TITLE
MISP querry Error

### ISSUE THREAD

**Issue by KlausItem** [Te-k/harpoon#115]
Hi

i expecting a Parser error while i try to querry my MISP
Anny Idea ??

```
harpoon misp -a uzot.png
Traceback (most recent call last):
  File "/home/cuckoo/.local/bin/harpoon", line 11, in <module>
    load_entry_point('harpoon==0.1.3', 'console_scripts', 'harpoon')()
  File "/home/cuckoo/.local/lib/python3.6/site-packages/harpoon/main.py", line 61, in main
    plugins[args.command].run(config, args, plugins)
  File "/home/cuckoo/.local/lib/python3.6/site-packages/harpoon/commands/misp.py", line 45, in run
    res = server.attributes.search(value=args.attr)
  File "/home/cuckoo/.local/lib/python3.6/site-packages/mispy/misp.py", line 818, in search
    response = objectify.fromstring(raw)
  File "src/lxml/objectify.pyx", line 1801, in lxml.objectify.fromstring
  File "src/lxml/etree.pyx", line 3213, in lxml.etree.fromstring
  File "src/lxml/parser.pxi", line 1877, in lxml.etree._parseMemoryDocument
  File "src/lxml/parser.pxi", line 1765, in lxml.etree._parseDoc
  File "src/lxml/parser.pxi", line 1127, in lxml.etree._BaseParser._parseDoc
  File "src/lxml/parser.pxi", line 601, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 711, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 640, in lxml.etree._raiseParseError
  File "<string>", line 1
lxml.etree.XMLSyntaxError: Start tag expected, '<' not found, line 1, column 1
```

**Comment by Te-k** [comment]
Hi, this is a known bug from mispy, I need to migrate to pymisp, I am adding this to the list of things to do.

**Comment by Te-k** [comment]
It took some time but it is fixed now, I just committed some code to fix it. I close the issue, let me know if you find any issue with it.
