### ISSUE TITLE
Config check don't work

### ISSUE THREAD

**Issue by zaqes** [Te-k/harpoon#147]
After an update the config check don't work for me.
I have no API keys set

```
Configuration check:
-urlscan	 -> OK
Traceback (most recent call last):
  File "/Users/thdfir/irshell/venv3/bin/harpoon", line 8, in <module>
    sys.exit(main())
  File "/Users/thdfir/irshell/venv3/lib/python3.9/site-packages/harpoon/main.py", line 61, in main
    plugins[args.command].run(config, args, plugins)
  File "/Users/thdfir/irshell/venv3/lib/python3.9/site-packages/harpoon/commands/config.py", line 43, in run
    if plugins[p].config_needed:
  File "/Users/thdfir/irshell/venv3/lib/python3.9/site-packages/harpoon/commands/base.py", line 9, in config_needed
    pname = list(self.config.keys())[0]
IndexError: list index out of range
```

**Comment by Te-k** [comment]
Hi, thanks for reporting this bug.
I just pushed a commit that should fix this bug, could you try with the last update from the git repo?

Thanks

**Comment by zaqes** [comment]
Can you push it to the pip3 repo?

**Comment by Te-k** [comment]
I don't want to push to pip something that has not been tested and confirmed working yet, but you can install it directly from the git repository with `pip install git+https://github.com/Te-k/harpoon.git`

**Comment by zaqes** [comment]
Ok.

That worked!

**Comment by Te-k** [comment]
Thanks, i will push that on pypi
