### ISSUE TITLE
quad9 timeout issue

### ISSUE THREAD

**Issue by zaqes** [Te-k/harpoon#149]
It doesn't seem to handle a timeout at quad9 very well.

`[+] Checking Quad9...
Traceback (most recent call last):
  File "/Users/<user>/<folder>/venv3/lib/python3.9/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/Users/<user>/<folder>/venv3/lib/python3.9/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/Users/<user>/<folder>/venv3/lib/python3.9/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/<user>/<folder>/venv3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/Users/<user>/<folder>/venv3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/Users/<user>/<folder>/venv3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/Users/<user>/<folder>/venv3/lib/python3.9/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/Users/<user>/<folder>/venv3/lib/python3.9/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x110b1a820>: Failed to establish a new connection: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/<user>/<folder>/venv3/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/Users/<user>/<folder>/venv3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/Users/<user>/<folder>/venv3/lib/python3.9/site-packages/urllib3/util/retry.py", line 573, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='dns.quad9.net', port=5053): Max retries exceeded with url: /dns-query?name=<domain>&type=A&ct=application%2Fdns-json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x110b1a820>: Failed to establish a new connection: [Errno 60] Operation timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/<user>/<folder>/venv3/bin/harpoon", line 8, in <module>
    sys.exit(main())
  File "/Users/<user>/<folder>/venv3/lib/python3.9/site-packages/harpoon/main.py", line 61, in main
    plugins[args.command].run(config, args, plugins)
  File "/Users/<user>/<folder>/venv3/lib/python3.9/site-packages/harpoon/commands/intel.py", line 70, in run
    plugins[p].intel("domain", unbracket(args.DOMAIN), data, conf)
  File "/Users/<user>/<folder>/venv3/lib/python3.9/site-packages/harpoon/commands/quad9.py", line 55, in intel
    r = requests.get("https://dns.quad9.net:5053/dns-query", params=params)
  File "/Users/<user>/<folder>/venv3/lib/python3.9/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/Users/<user>/<folder>/venv3/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/<user>/<folder>/venv3/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/<user>/<folder>/venv3/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/Users/<user>/<folder>/venv3/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='dns.quad9.net', port=5053): Max retries exceeded with url: /dns-query?name=<domain>&type=A&ct=application%2Fdns-json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x110b1a820>: Failed to establish a new connection: [Errno 60] Operation timed out'))`

**Comment by Te-k** [comment]
Thanks, this needs to be fixed
