### ISSUE TITLE
Unable to use Goo.gl shortner with dev api

### ISSUE THREAD

**Issue by cucx** [Te-k/harpoon#55]
Hello! Not sure if this is a bug, or simply me not finding the right token/API.
If I use a Google API and try the short URL I get the following:
```
harpoon googl -H kAoRcD
Traceback (most recent call last):
  File "/usr/local/bin/harpoon", line 11, in <module>
    load_entry_point('harpoon==0.1.1', 'console_scripts', 'harpoon')()
  File "/usr/local/lib/python3.6/dist-packages/harpoon-0.1.1-py3.6.egg/harpoon/main.py", line 52, in main
    plugins[args.command].run(config, args, plugins)
  File "/usr/local/lib/python3.6/dist-packages/harpoon-0.1.1-py3.6.egg/harpoon/commands/googl.py", line 29, in run
    go = GoogleShortener(config['Googl']['token'])
NameError: name 'config' is not defined
```
However I if I use the other version here https://github.com/Te-k/analyst-scripts/tree/master/goo.gl with same credentials, i get no such issues (and works fine).

```
    "created":"2018-02-23T03:39:58.850+00:00",
    "id":"http://goo.gl/kAoRcD",
    "kind":"urlshortener#url",
    "longUrl":"http://REDACTED",
    "status":"OK"
}
```
Am i missing something in the latest version?

**Comment by Te-k** [comment]
Ah indeed, it was a stupid typo, it should work now

**Comment by cucx** [comment]
ah perfect thanks! confirmed as working.
