### ISSUE TITLE
"SyntaxError: invalid syntax" occurs when  delivering command "harpoon config -u"

### ISSUE THREAD

**Issue by limengmingx** [Te-k/harpoon#56]
After installing the requirement ,harpoon and phantomjs and using command "harpoon config -u",error happends :
```
root@ubuntu:/harpoon/harpoon-master# harpoon config -u
2018-02-28 21:25:51+0800 [-] Log opened.
2018-02-28 21:25:51+0800 [-] Traceback (most recent call last):
2018-02-28 21:25:51+0800 [-]   File "/usr/local/bin/harpoon", line 9, in <module>
2018-02-28 21:25:51+0800 [-]     from harpoon.site import Visualiser
2018-02-28 21:25:51+0800 [-]   File "/usr/local/lib/python3.5/dist-packages/harpoon/site.py", line 22
2018-02-28 21:25:51+0800 [-]     except Exception,e:
2018-02-28 21:25:51+0800 [-]                     ^
2018-02-28 21:25:51+0800 [-] SyntaxError: invalid syntax
```
I am using ubuntu 16.04 and python 3.5.2
Any suggestions would be welcomed ,thanks！

**Comment by limengmingx** [comment]
Have I missied something necessary?

**Comment by Te-k** [comment]
It is really weird because the Syntax Error does not seem to come from Harpoon code. I guess it is a weird bug in python install ?
How did you install harpoon ?

**Comment by mlaferrera** [comment]
It looks like @limengmingx installed via pypi (https://pypi.python.org/pypi/Harpoon), rather than from this repo.

**Comment by Te-k** [comment]
Oh shit, I missed that there was already a Harpoon on pypi :(, it sucks because this package is from 2011 and does not seem updated.
Is there any way to solve that ?

**Comment by mlaferrera** [comment]
It looks like you may need to contact the owner of the current one and ask. If that doesn't work, there is a process: https://www.python.org/dev/peps/pep-0541/#removal-of-an-abandoned-project

**Comment by limengmingx** [comment]
sorry for my  late response.
I download the full code and do :
sudo pip3 install -r requirements.txt
sudo python3 setup.py install
and get the error above

**Comment by limengmingx** [comment]
I dont know how to deal with it and change to using another computer ( linux 16.04 and python3 ),and after command:
```
git clone https://github.com/Te-k/harpoon.git
cd harpoon
sudo pip3 install -r requirements.txt
sudo python3 setup.py install
```
and send the command 
`harpoon --help`
I get the error 
```
Traceback (most recent call last):
  File "/usr/local/bin/harpoon", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2927, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2913, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2940, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 635, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 943, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 829, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pycrtsh' distribution was not found and is required by harpoon

```
: ( I still cannot using Harpoon

**Comment by Te-k** [comment]
Can you check if pycrtsh is installed with `pip list | fgrep pycrtsh` ?

**Comment by Te-k** [comment]
You need to install censys, it is part of dependencies, so `pip3 install -e requirements.txt` should solve your problem (if not, I don't get why)
(Also you should _really_ install virtualenv)

**Comment by Te-k** [comment]
That was a long time ago, I close, feel free to reopen it if you still have this problem
