### ISSUE TITLE
Invalid Syntax error Telethon - New install

### ISSUE THREAD

**Issue by parker67** [Te-k/harpoon#58]
Hi, 

Im installing this on a fresh Ubuntu 1604. 
Here are the commands i ran for replication. 

1. git clone https://github.com/Te-k/harpoon.git
2. cd harpoon
3. sudo pip install . --process-dependency-links
4. harpoon 

Below is the error that i get. 
```
Traceback (most recent call last):
  File "/usr/local/bin/harpoon", line 9, in <module>
    load_entry_point('harpoon==0.1.1', 'console_scripts', 'harpoon')()
  File "/usr/local/lib/python2.7/dist-packages/harpoon-0.1.1-py2.7.egg/harpoon/main.py", line 31, in main
    plugins = init_plugins()
  File "/usr/local/lib/python2.7/dist-packages/harpoon-0.1.1-py2.7.egg/harpoon/main.py", line 18, in init_plugins
    mod = __import__(plugin)
  File "/usr/local/lib/python2.7/dist-packages/harpoon-0.1.1-py2.7.egg/harpoon/commands/telegram.py", line 4, in <module>
    import telethon
  File "/usr/local/lib/python2.7/dist-packages/telethon/__init__.py", line 2, in <module>
    from .telegram_bare_client import TelegramBareClient
  File "/usr/local/lib/python2.7/dist-packages/telethon/telegram_bare_client.py", line 414
    def __call__(self, *requests, retries=5):
                                        ^
SyntaxError: invalid syntax
```

Did i miss something?

Cheers

**Comment by Te-k** [comment]
I don't know what is the issue but Harpoon only works in python3 anyway. Can you try the same in python3 ?

**Comment by parker67** [comment]
had to reinstall with 
sudo pip3 install . --process-dependency-links

and now it works. might be worth mentioning in the install instructions that it should be the python 3 version of pip to use. 

Thanks for your help anyway 👍 Love the tool.
