### ISSUE TITLE
Add support for "REMOVED" goog.gl expanding when using a list

### ISSUE THREAD

**Issue by cucx** [Te-k/harpoon#59]
When a Goog/gl short URL is removed, the `harpoon goog.gl -f 3` fails.  Would be great to add support for these.
```
harpoon googl -H 1c2SdZ
{
    "id":"http://goo.gl/1c2SdZ",
    "kind":"urlshortener#url",
    "status":"REMOVED"
}
```

```
:~/harpoon# cat 3
1c2SdZ
295NKq
```
```
:~/harpoon# harpoon googl -f 3
Date;Short URL;Long URL;Analytics;Short URL Clicks;Long URL Clicks
Traceback (most recent call last):
  File "/usr/local/bin/harpoon", line 11, in <module>
    load_entry_point('harpoon==0.1.1', 'console_scripts', 'harpoon')()
  File "/usr/local/lib/python3.6/dist-packages/harpoon-0.1.1-py3.6.egg/harpoon/main.py", line 52, in main
    plugins[args.command].run(config, args, plugins)
  File "/usr/local/lib/python3.6/dist-packages/harpoon-0.1.1-py3.6.egg/harpoon/commands/googl.py", line 41, in run
    res["created"],
KeyError: 'created'
```

**Comment by Te-k** [comment]
Nice catch, will fix that next week :+1: (except if anyone want to do it before)

**Comment by Te-k** [comment]
@mlaferrera fixed that, let me know if you have any other issue

**Comment by Te-k** [comment]
Ok, closing the ticket now, feel free to reopen it of it is still not working for you
