### ISSUE TITLE
harpoon config -u

### ISSUE THREAD

**Issue by jkopensource** [Te-k/harpoon#61]
Updating all plugins data:
Updating plugin ip
Downloading MaxMind GeoIP Database
-GeoLite2-City.mmdb
-GeoLite2-ASN.mmdb
Download ASN Name database
-asnname.csv
Downloading CIDR data
Traceback (most recent call last):
  File "/usr/local/bin/harpoon", line 9, in <module>
    load_entry_point('harpoon==0.1.1', 'console_scripts', 'harpoon')()
  File "/usr/local/lib/python3.5/dist-packages/harpoon-0.1.1-py3.5.egg/harpoon/main.py", line 52, in main
    plugins[args.command].run(config, args, plugins)
  File "/usr/local/lib/python3.5/dist-packages/harpoon-0.1.1-py3.5.egg/harpoon/commands/config.py", line 68, in run
    plugins[p].update()
  File "/usr/local/lib/python3.5/dist-packages/harpoon-0.1.1-py3.5.egg/harpoon/commands/ip.py", line 122, in update
    subprocess.call(["pyasn_util_download.py", "--latest"])
  File "/usr/lib/python3.5/subprocess.py", line 557, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'pyasn_util_download.py'

**Comment by Te-k** [comment]
Can you check that you have `pyasn` installed ? (with `pip list | fgrep -i pyasn` for instance)
