### ISSUE TITLE
KeyError when trying harpoon commands

### ISSUE THREAD

**Issue by magedrifter** [Te-k/harpoon#85]
Good day,
I have just recently installed the project using pip3, having created a virtualenv for the project. And when trying to test harpoon with 'harpoon config', i got this error : 
```
Traceback (most recent call last):
  File "Python36-32\Scripts\harpoon-script.py", line 11, in <module>
    load_entry_point('harpoon==0.1.1', 'console_scripts', 'harpoon')()
  File "python36-32\lib\site-packages\harpoon\main.py", line 31, in main
    plugins = init_plugins()
  File "python36-32\lib\site-packages\harpoon\main.py", line 18, in init_plugins
    mod = __import__(plugin)
  File "python36-32\lib\site-packages\harpoon/commands\misp.py", line 5, in <module>
    from mispy import MispServer, MispEvent
  File "python36-32\lib\site-packages\mispy\__init__.py", line 1, in <module>
    from .misp import MispTag, MispEvent, MispServer, MispAttribute, MispShadowAttribute, MispTransportError
  File "python36-32\lib\site-packages\mispy\misp.py", line 54, in <module>
    MISP_API_KEY = open(os.path.join(os.environ['HOME'], '.misp_api_key')).read().strip()
  File "python36-32\lib\os.py", line 669, in __getitem__
    raise KeyError(key) from None
KeyError: 'HOME'
```

Might there be a solution for this? Thanks in advance!

**Comment by Te-k** [comment]
This is actually a problem in [mispy](https://github.com/nbareil/mispy) because you don't have $HOME defined. I have created [an issue](https://github.com/nbareil/mispy/issues/13) in MISPy for that.
Could you tell me what OS you are using ? Windows I guess ? 

**Short term fix :** add a HOME environment variable (whatever the value is)
**Long term fix :** fix the bug in MISPy 

Overall, I don't think many people have tested Harpoon on Windows (I have not) so you should definitely expect more bugs like this one. Feel free to open issues for each one of them. 
Thanks

**Comment by magedrifter** [comment]
Thanks for the response! 
Was not aware the tools was only optimized for linux, will stick to using it in linux then
