### ISSUE TITLE
Telethon issue running on MacOS

### ISSUE THREAD

**Issue by mbower** [Te-k/harpoon#87]
I'm having an issue getting harpoon to run on MacOS. It worked previously, but python was upgraded and broke something. 

OS version: 10.13.5
Python: 3.7.0

I get the following trying to run `harpoon config`

`Traceback (most recent call last):
  File "/usr/local/bin/harpoon", line 11, in <module>
    load_entry_point('harpoon==0.1.1', 'console_scripts', 'harpoon')()
  File "/usr/local/lib/python3.7/site-packages/harpoon/main.py", line 31, in main
    plugins = init_plugins()
  File "/usr/local/lib/python3.7/site-packages/harpoon/main.py", line 18, in init_plugins
    mod = __import__(plugin)
  File "/usr/local/lib/python3.7/site-packages/harpoon/commands/telegram.py", line 12, in <module>
    from telethon.errors.rpc_error_list import ChatAdminRequiredError
ModuleNotFoundError: No module named 'telethon.errors.rpc_error_list'`

Telethon version: 1.0.2

**Comment by Timbosec** [comment]
Getting an identical error here

**Comment by Te-k** [comment]
The current harpoon version works with Telethon 0.18.3.

I have updated the requirements to force the usage of this version. You can also install it manually with `pip install Telethon==0.18.3`
